version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: frc
      POSTGRES_PASSWORD: frcpass
      POSTGRES_DB: scouting
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data